name: snake_detector_app
description: ""
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-50.0.dev

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  retrofit: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
